"""
Data models for SSC CGL syllabus topics and lesson plans.
Supports 4 subjects (reasoning, quant, english, general_awareness) and
two daily release slots (morning / evening).
"""

from dataclasses import dataclass, field
from typing import List, Optional


# Human-readable subject names for narration and on-screen display
SUBJECT_DISPLAY = {
    "reasoning": "General Intelligence & Reasoning",
    "quant": "Quantitative Aptitude",
    "english": "English Comprehension",
    "general_awareness": "General Awareness",
}

# Short Hindi-friendly subject names spoken in narration
SUBJECT_SPOKEN = {
    "reasoning": "Reasoning",
    "quant": "Maths",
    "english": "English",
    "general_awareness": "General Awareness",
}


@dataclass
class Topic:
    """Represents a single topic in the SSC CGL syllabus."""
    part: int
    title: str
    category: str  # reasoning | quant | english | general_awareness
    slot: str = "morning"  # morning | evening
    subtopics: List[str] = field(default_factory=list)
    difficulty: str = "intermediate"
    formulas: List[str] = field(default_factory=list)
    duration_target_minutes: int = 12

    @property
    def category_display(self) -> str:
        return SUBJECT_DISPLAY.get(self.category, self.category.replace("_", " ").title())

    @property
    def subject_spoken(self) -> str:
        return SUBJECT_SPOKEN.get(self.category, self.category_display)


@dataclass
class FormulaBlock:
    """A formula/rule with explanation for display."""
    formula: str
    explanation: str
    visual_label: str = ""


@dataclass
class Example:
    """A solved example with step-by-step solution."""
    question: str
    steps: List[str] = field(default_factory=list)
    answer: str = ""
    explanation: str = ""


@dataclass
class Question:
    """A practice question with options."""
    question: str
    options: List[str] = field(default_factory=list)  # ["A) ...", "B) ...", ...]
    correct_answer: str = ""
    explanation: str = ""


@dataclass
class LessonPlan:
    """Complete lesson plan generated by LLM."""
    topic: Topic
    introduction: str = ""
    concept_explanation: str = ""
    formulas: List[FormulaBlock] = field(default_factory=list)
    solved_examples: List[Example] = field(default_factory=list)
    tips_and_tricks: List[str] = field(default_factory=list)
    practice_questions: List[Question] = field(default_factory=list)
    summary_points: List[str] = field(default_factory=list)

    def get_narration_text(self) -> str:
        """Full Hinglish narration for TTS, with CGL welcome intro and outro CTA."""
        parts = []
        subject = self.topic.subject_spoken

        # ---- Intro welcome (spoken at the very beginning) ----
        parts.append(
            f"Namaste doston! SSC CGL Complete Preparation mein aapka swagat hai. "
            f"Aaj ki class {subject} subject ki hai. "
            f"Doston, yeh video aapke SSC CGL exam ke liye bahut important hai, "
            f"toh please last tak zaroor dekhiye. "
            f"Maine is video ke end mein aur comment section mein kuch bahut important "
            f"practice questions share kiye hain jo aapke exam mein zaroor aayenge, "
            f"toh video poora dekhiye aur comment section zaroor check kariye. "
            f"Chaliye shuru karte hain!"
        )

        if self.introduction:
            parts.append(self.introduction)

        if self.concept_explanation:
            parts.append(self.concept_explanation)

        for fb in self.formulas:
            parts.append(fb.explanation)

        for ex in self.solved_examples:
            parts.append(ex.question)
            for step in ex.steps:
                parts.append(step)
            parts.append(ex.answer + ". " + ex.explanation if ex.explanation else ex.answer)

        for tip in self.tips_and_tricks:
            parts.append(tip)

        if self.practice_questions:
            parts.append(
                f"Practice question number 1. {self.practice_questions[0].question}. "
                f"Iska answer pinned comment mein check kariye."
            )

        for point in self.summary_points:
            parts.append(point)

        # ---- Outro CTA (spoken at the very end) ----
        parts.append(
            f"Toh doston, aaj ka topic yahan pe complete hota hai. "
            f"Umeed karta hoon aapko yeh {subject} ki class helpful lagi hogi. "
            f"Doston, maine comment section mein kuch bahut important practice questions "
            f"share kiye hain jo SSC CGL previous year exams mein baar baar puche gaye hain. "
            f"Please in questions ko zaroor solve kariye aur apna answer comment mein likhiye, "
            f"main aapko reply karunga ki sahi hai ya galat. "
            f"Agar yeh video aapko achhi lagi toh please like button dabayiye, "
            f"isse mujhe motivation milta hai aur aapke liye aur achhe videos banane mein madad hoti hai. "
            f"Aur agar aapne abhi tak channel subscribe nahi kiya hai toh abhi kariye "
            f"aur bell icon zaroor dabayiye taaki har nayi video ki notification aapko mil sake. "
            f"Doston, yeh SSC CGL ki complete series hai jisme Reasoning, Maths, English aur "
            f"General Awareness — chaaron subjects cover honge. "
            f"Roz subah aur shaam nayi video aati hai, ek bhi video mat miss kariye. "
            f"Agar aapne poori series complete kar li toh exam mein ek bhi question galat nahi hoga, "
            f"yeh mera promise hai. "
            f"Apne doston ko bhi share kariye jinko SSC CGL ki tayari karni hai. "
            f"Milte hain agli class mein. Tab tak practice karte rahiye! Jai Hind!"
        )

        return " ... ".join(parts)

    def get_study_notes(self) -> str:
        """Formatted study notes for the YouTube comment."""
        lines = ["KEY CONCEPTS:"]
        if self.concept_explanation:
            for s in self.concept_explanation.split(". ")[:3]:
                lines.append(f"  - {s.strip()}")

        if self.formulas:
            lines.append("\nIMPORTANT FORMULAS:")
            for fb in self.formulas:
                lines.append(f"  {fb.formula}")

        if self.tips_and_tricks:
            lines.append("\nTIPS & TRICKS:")
            for i, tip in enumerate(self.tips_and_tricks, 1):
                lines.append(f"  {i}. {tip}")

        return "\n".join(lines)

    def get_practice_text(self) -> str:
        """Formatted practice questions for the YouTube comment."""
        lines = []
        for i, q in enumerate(self.practice_questions, 1):
            lines.append(f"Q{i}. {q.question}")
            for opt in q.options:
                lines.append(f"  {opt}")
            lines.append("")
        return "\n".join(lines)

    def get_answer_key(self) -> str:
        """Answer key for practice questions."""
        lines = []
        for i, q in enumerate(self.practice_questions, 1):
            lines.append(f"Q{i}: {q.correct_answer}")
            if q.explanation:
                lines.append(f"   Explanation: {q.explanation}")
        return "\n".join(lines)
